# Generated by Django 4.1 on 2023-09-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='categories',
            field=models.ManyToManyField(null=True, to='core.category'),
        ),
    ]
